stages:
  - build
  - tag
  - release

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests"

# Run only on pushes to main
workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - mvn $MAVEN_CLI_OPTS package
    - VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - echo "Version: $VERSION"
    - echo $VERSION > version.txt
  artifacts:
    paths:
      - target/*.jar
      - version.txt
    expire_in: 1 hour

tag:
  stage: tag
  image: alpine/git
  dependencies:
    - build
  script:
    - VERSION=$(cat version.txt)
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
    - git tag -a "v$VERSION" -m "Release v$VERSION"
    - git push origin "v$VERSION"
  only:
    - main


