#Turn this on or off, If it is on it will give plenty of extra information into the console to help to debug some issues
debug: true

# Right now the only option for this is en_us but we can add other languages in the future
Language: en_us

Party:
  maxSize: 6
  # The amount of time to wait for a player to be offline before they get removed from the party
  offlineTimeoutMinutes: 1
