name: PartyPlugin
main: com.Blakeoo2.Main
version: '${project.version}'
api-version: 1.21
authors:
  - Blakeoo2
Description: Party plugin manager


commands:
  party:
    description: Base party command
    usage: /party <create/invite/accept/disband/leave/chat>
    aliases:
      - p

  partychat:
    description: Command shortcut for /party chat
    usage: /partychat (message)
    aliases:
      - pc
      - pchat
      - partyc

permissions:
  PartyPlugin.bypass.maxSize:
    default: op
    description: Allows the user to join a party when it is full


  PartyPlugin.admin.*:
    default: op
    description: Permission node for all admin party command
    children:
      - PartyPlugin.admin.reload
      - PartyPlugin.admin.socialspy
      - PartyPlugin.admin
      - PartyPlugin.admin.seeParty

  PartyPlugin.admin:
    default: op
    description: base permission node for admin, have to have this one one or none of them will work


  PartyPlugin.admin.reload:
    default: op
    description: Allows the admin to reload all config files.

  PartyPlugin.admin.socialspy:
    default: op
    description: Allows the user to see all party chat messages, doesn't matter what party they are in themselves

  PartyPlugin.admin.seeParty:
    default: op
    description: Allows the user to be able to see the members of another party